---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc variables
      include_vars: vars/vpc_setup

    - name: create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
        tenancy: default
      register: vpc_out

    - debug:
        var: vpc_out.vpc.id