---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc variables
      include_vars: vars/vpc_setup

    - name: create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
        tenancy: default
      register: vpc_out

    - name: create public subnet1
      ec2_vpc_subnet:
        vpc_id: "vpc_out.vpc.id"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pusub1Cidr}}"
        map_public: yes
        state: "{{state}}"
        wait: yes
        tags:
          Name: pubsub1
      register: pubsub1_out


