---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc variables
      include_vars: vars/vpc_setup

    - name: create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
        tenancy: default
      register: vpc_out

    - name: create public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{pubsub1Cidr}}"
        map_public: yes
        state: "{{state}}"
        wait: yes
        tags:
          Name: pubsub1
      register: pubsub1_out

    - name: create public subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{pubsub2Cidr}}"
        map_public: yes
        state: "{{state}}"
        wait: yes
        tags:
          Name: pubsub2
      register: pubsub2_out

    - name: create public subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{pubsub3Cidr}}"
        map_public: yes
        state: "{{state}}"
        wait: yes
        tags:
          Name: pubsub3
      register: pubsub3_out

    - name: create private subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{prisub1Cidr}}"
        state: "{{state}}"
        wait: yes
        tags:
          Name: prisub1
      register: prisub1_out

    - name: create private subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{prisub2Cidr}}"
        state: "{{state}}"
        wait: yes
        tags:
          Name: prisub2
      register: prisub2_out

    - name: create private subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{prisub3Cidr}}"
        state: "{{state}}"
        wait: yes
        tags:
          Name: prisub3
      register: prisub3_out

    - name: create internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
      register: igw_out




